version: '3.8'

services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yashodhan
      POSTGRES_DB: dockerPoc
    ports:
      - "5433:5432"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mongodatabase
volumes:
  mongo-data: